#!/usr/bin/env python3
"""Generate cards.js from cards.json.

cards.json is the data you edit. cards.js is what index.html and gallery.html load
(a plain <script src> works from file:// and from GitHub Pages, fetch() does not).

Run after any change to cards.json:

    python3 build.py

The script also tolerates a "full" pipeline export: paint entries whose confidence
is "placeholder" and internal workflow fields are dropped from the output, and the
slimmed result is written back to cards.json so the two files never drift.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "cards.json"
OUT = HERE / "cards.js"

CARD_FIELDS = ("id", "theme", "title", "mood", "art_front", "colors", "challenge_hint")
COLOR_FIELDS = ("name", "hex", "role", "paints")
PAINT_FIELDS = ("name", "code", "confidence", "mix", "note")


def pick(d, fields):
    return {k: d[k] for k in fields if k in d and d[k] not in (None, "", {}, [])}


def slim_card(card):
    out = pick(card, CARD_FIELDS)
    colors = []
    for color in card.get("colors", []):
        c = pick(color, COLOR_FIELDS)
        paints = {}
        for brand, paint in color.get("paints", {}).items():
            if paint.get("confidence") == "placeholder":
                continue
            name = (paint.get("name") or "").strip()
            if name in ("", "-", "—"):
                continue
            paints[brand] = pick(paint, PAINT_FIELDS)
        c["paints"] = paints
        colors.append(c)
    out["colors"] = colors
    return out


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    meta = data.get("meta", {})
    cards = [slim_card(c) for c in data.get("cards", [])]

    ids = [c["id"] for c in cards]
    assert len(ids) == len(set(ids)), "duplicate card ids"
    for c in cards:
        assert len(c["colors"]) == 5, f"{c['id']} has {len(c['colors'])} colors"
        for col in c["colors"]:
            assert "PRO" in col["paints"], f"{c['id']} / {col['name']} has no PRO match"
        art = HERE / c["art_front"]
        assert art.exists(), f"{c['id']} art missing: {c['art_front']}"

    slim = {"meta": meta, "cards": cards}
    SRC.write_text(json.dumps(slim, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    js = "// Generated by build.py from cards.json. Do not edit by hand.\n"
    js += "window.DECK = " + json.dumps(slim, separators=(",", ":"), ensure_ascii=False) + ";\n"
    OUT.write_text(js, encoding="utf-8")

    fantasy = sum(1 for c in cards if c["theme"] == "fantasy")
    print(f"{len(cards)} cards ({fantasy} fantasy, {len(cards) - fantasy} sci-fi)")
    print(f"cards.json {SRC.stat().st_size // 1024} KB, cards.js {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
